### ISSUE TITLE
TODO: Add CB-Webtool to docker-compose.yaml

### ISSUE THREAD

**Issue by jihoon-seo** [jihoon-seo/cb-deployer#33]
Ref: https://github.com/cloud-barista/cb-webtool/blob/master/docker-compose.yaml
```yaml
version: '3.1'

services: 
    webtool:
        build: .
        image: cb-webtool-docker-compose
        ports:
            - 1234:1234
        container_name: cb-webtool
        environment:
            - API_GW=http://localhost:8000
            - SPIDER_URL=http://localhost:8000/spider
            - TUMBLE_URL=http://localhost:8000/tumblebug
            - DRAGONFLY_URL=http://localhost:8000/dragonfly
            - LADYBUG_URL=http://localhost:8000/ladybug
```
